# Generated by Django 3.0.7 on 2020-06-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personas',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personas',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
