# Generated by Django 3.0.7 on 2020-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20200618_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='donador',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
