# Generated by Django 3.0.7 on 2020-06-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_personas_donador'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='email',
            field=models.EmailField(default='@', max_length=254),
            preserve_default=False,
        ),
    ]
