# Generated by Django 3.0.7 on 2020-06-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_personas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
